# Site settings
title: Riley Auto Detail
email: rileyautodetail@domain.com
url: https://silverado5300.github.io
description: "Mobile auto detailing Livingston County Michigan"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  
  - title: facebook
    url: https://www.facebook.com/RileyAutoDetailing
  - title: instagram
    url: http://instagram.com/riley_autodetailing

# Build settings
markdown: kramdown
permalink: pretty
